language: ruby
rvm:
  - 2.5.0

before_script:
  - bundle install
  - psql -c 'create database pgapp_test;' -u postgres
  - bin/rails db:migrate 

dist: trusty


script:
  - bundle exec rspec

services: 
  -postgresql


